name: .NET

on:
  push:
    branches: [ "main", "feat-go2climb-tests" ]
  pull_request:
    branches: [ "main", "feat-go2climb-tests" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Go2Climb.API/Go2Climb.API.Specflow.AcceptanceTests
